steps:
  - id: "go version"
    name: golang
    args: [ 'go', 'version' ]
#    env: [ "GOPATH=/" ]

  - id: "go test"
    name: golang
    args: [ 'go', 'test' ]
#    env: [ "GOPATH=/" ]

images:
  - 'gcr.io/$PROJECT_ID/cm-sum:latest'