steps:
  - id: "go version"
    name: 'gcr.io/cloud-builders/go'
    args: ['version']
    env: ["GOPATH=."]

  - id: "go test"
    name: 'gcr.io/cloud-builders/go'
    args: ['test']
    env: ["GOPATH=."]

images:
  - 'gcr.io/$PROJECT_ID/cm-sum:latest'