steps:
  - id: "go version"
    name: golang
    args: [ 'go', 'version' ]
    env: [ 'PROJECT_ROOT=github.com/faelplg/cm-sum' ]

  - id: "go test"
    name: golang
    args: [ 'go', 'test' ]
    env: [ 'PROJECT_ROOT=github.com/faelplg/cm-sum' ]

images:
  - 'gcr.io/$PROJECT_ID/cm-sum:latest'